---
title: "Лабораторная 2"
author: "Лыжина Мария"
date: "2022-12-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Задание 1

Вариант 3 = (15 + 15) % 27

Подключаем библиотеки
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
library(stringr)
```
Формируем датафрейм с информацией по федеральным округам, включая суммарные экспорт и импорт
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
create_data_frame <- function(data) {
  region_data = data[grep('округ$', data$Регион),]
  import_data = apply(region_data[grep('Импорт$', names(region_data))], 1, function(x) sum(as.numeric(str_replace_all(x, "-", "0"))))
  export_data = apply(region_data[grep('Экспорт$', names(region_data))], 1, function(x) sum(as.numeric(str_replace_all(x, "-", "0"))))
  region_data['СумИмпорт'] = import_data
  region_data['СумЭкспорт'] = export_data
  return (region_data)
}
```
Выбираем нужные регионы с экспортом, превалирующим над импортом
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
compare_export_import <- function(data) {
  return (subset(data, СумЭкспорт > СумИмпорт)$Регион)
}
```
Запускаем процесс
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
path = 'C:/Users/maria/gitprojects/R_labs/lab2/ExpImp.RData'
load(path)
region_data = create_data_frame(ExpImp)
print(region_data)
```

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
regions_exp = compare_export_import(region_data)
print(regions_exp)
```

Задание 2

Вариант 15 = 15 % 27

Ищем число больниц и среднее число умерших и вернувшихся
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
mean_patients <- function(state) {
  path = "C:/Users/maria/gitprojects/R_labs/lab2/outcome-of-care-measures.csv"
  data <- read.csv(path, colClasses = "character")
  state <-data[which(data$State == state),]
  
  hospitals_number <- length(unique(state$Hospital.Name))
  
  
  heart_attack_mortality <- state[,"Number.of.Patients...Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]
  heart_attack_mortality <- lapply(heart_attack_mortality, function(x) gsub("[^0-9.-]", NA, x))
  heart_attack_mortality <- lapply(heart_attack_mortality, function(x) as.numeric(x))
  heart_attack_mortality <- heart_attack_mortality[!is.na(heart_attack_mortality)]
  heart_attack_mortality_mean <- mean(unlist(heart_attack_mortality), na.rm=TRUE)
  
  heart_attack_readmission <- state[,"Number.of.Patients...Hospital.30.Day.Readmission.Rates.from.Heart.Attack"]
  heart_attack_readmission <- lapply(heart_attack_readmission, function(x) gsub("[^0-9.-]", NA, x))
  heart_attack_readmission <- lapply(heart_attack_readmission, function(x) as.numeric(x))
  heart_attack_readmission <- heart_attack_readmission[!is.na(heart_attack_readmission)]
  heart_attack_readmission_mean <- mean(unlist(heart_attack_readmission), na.rm=TRUE)
  
  
  heart_failure_mortality <- state[,"Number.of.Patients...Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure"]
  heart_failure_mortality <- lapply(heart_failure_mortality, function(x) gsub("[^0-9.-]", NA, x))
  heart_failure_mortality <- lapply(heart_failure_mortality, function(x) as.numeric(x))
  heart_failure_mortality <- heart_failure_mortality[!is.na(heart_failure_mortality)]
  heart_failure_mortality_mean <- mean(unlist(heart_failure_mortality), na.rm=TRUE)
  
  
  heart_failure_readmission <- state[,"Number.of.Patients...Hospital.30.Day.Readmission.Rates.from.Heart.Failure"]
  heart_failure_readmission <- lapply(heart_failure_readmission, function(x) gsub("[^0-9.-]", NA, x))
  heart_failure_readmission <- lapply(heart_failure_readmission, function(x) as.numeric(x))
  heart_failure_readmission <- heart_failure_readmission[!is.na(heart_failure_readmission)]
  heart_failure_readmission_mean <- mean(unlist(heart_failure_readmission), na.rm=TRUE)
  
  
  pneumonia_mortality <-state[,"Number.of.Patients...Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia",]
  pneumonia_mortality <- lapply(pneumonia_mortality, function(x) gsub("[^0-9.-]", NA, x))
  pneumonia_mortality <- lapply(pneumonia_mortality, function(x) as.numeric(x))
  pneumonia_mortality <- pneumonia_mortality[!is.na(pneumonia_mortality)]
  pneumonia_mortality_mean <- mean(unlist(pneumonia_mortality), na.rm=TRUE)
  
  
  pneumonia_readmission <-state[,"Number.of.Patients...Hospital.30.Day.Readmission.Rates.from.Pneumonia",]
  pneumonia_readmission <- lapply(pneumonia_readmission, function(x) gsub("[^0-9.-]", NA, x))
  pneumonia_readmission <- lapply(pneumonia_readmission, function(x) as.numeric(x))
  pneumonia_readmission <- pneumonia_readmission[!is.na(pneumonia_readmission)]
  pneumonia_readmission_mean <- mean(unlist(pneumonia_readmission), na.rm=TRUE)
  
  values <- list(hospitals_number, heart_attack_mortality_mean, heart_attack_readmission_mean, heart_failure_mortality_mean,heart_failure_readmission_mean,pneumonia_mortality_mean,pneumonia_readmission_mean)
  names(values) <- c("Number of hospitals", "Heart Attack Mortality mean", "Heart Attack Readmission mean", "Heart Failure Mortality mean", "Heart Failure Readmission mean", "Pneumonia Mortality mean", "Pneumonia Readmission mean")
  return(values)
}
```
Запускаем процесс
```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
state <- "AL"
mean_patients(state)
```